version: '3.1'

services:
  db:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    container_name: mysql5.7
    copy:
      - ./data:/var/lib/mysql
  ports:
    - 3306:3306

  ```